version: '3'

services:
  audio-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./recordings:/app/recordings
      - ./transcripts:/app/transcripts
      - ./responses:/app/responses
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 