version: '3'

services:
  audio-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./recordings:/app/recordings
      - ./transcripts:/app/transcripts
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1 